name: Autopost

on:
  schedule:
    - cron: '0 7 * * *' # каждый день в 7 утра
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate posts
        run: |
          mkdir -p blog
          echo "Статья обновлена $(date)" > blog/post-$(date +%F).md
      - name: Commit
        run: |
          git config --local user.name "ViktoriaBot"
          git config --local user.email "bot@example.com"
          git add .
          git commit -m "auto post"
          git push
